### ISSUE TITLE
Rename the language?

### ISSUE THREAD

**Issue by faultyserver** [myst-lang/myst#12]
This is more of a scratchpad for ideas than anything else.

I generally like the name Myst, but I'm not attached to it in any way. I have also been feeling like it doesn't particularly match the language's look and feel. That's obviously subjective and it's hard to explain it, it's mainly a gut feeling that's grown over time.

I also don't have any other ideas for names, but here are a few guidelines for a great name (at least in my eyes):

- **The domain `<new-name>-lang.org` should be publicly available for purchase.** `-lang` is essentially a standard nowadays, and I don't want to miss out on that just because of a new name. Ideally the domain isn't parked, either (though parking any suggestions made here for later transfer might be a good idea).
- **There should be a corresponding name for people who use the language.** Python users are Pythonistas, which is a little odd, but the correlation is obvious, and better than Ruby users being called Rubyers. Elixir users are Elixirists, Rust users are Rustaceans, etc. Something similar to that would be great to have (side note Myst users being called Mysters seems kind of bad...).
- **The name should reflect something about the language.** This one is a bit out there, but the name Crystal matches it's relation to Ruby, it's a more-structured, "clearer" (e.g., faster) language, but still in the same "family", so to speak. For Myst, I wouldn't want to rename it to "2-ton brick", because that doesn't match the feel of the language to me (and it's just a bad name). I see Myst as more of a lightweight, but with structure that can be introduced where it is helpful. Kind of like a non-newtonian fluid, if you will.
- **No more than 2-3 syllables.** One syllable is a little to short to me. Go, Rust, Lisp, they're kind of easy to miss when speaking quickly. Two syllable names have a little more impact: Python, Ruby, Crystal, Erlang, Prolog. 3 syllable names are okay, but start feeling a little too long sometimes: Elixir, C++, JavaScript (need I say more?). 4 is just too many.

I'll probably add to this list of guidelines over time, but those are essentially the criteria that I've been judging names by so far.

**Note:** This is not a decision that will be taken lightly. Renaming a language is already a big deal, particularly once it gains some semblance of popularity. Renaming a language _more than once_ could mean cascading changes and weeks or months of transition time. I can't imagine actually changing the name of the language before a `v0.5.0` or so, or after a `v1.0`. A name change after `v1.0` would need substantial reasoning to do so.

**Comment by haleymoore** [comment]
I had a thought. Bevel and bezel - both can be applied to the stone category (the idea came from this, not that it has to have that relation to work). 

I lean more toward to bezel for phonetic reasons. I can visually think of some ideas that could tag alone with it that may be less cliche then they would with bevel.

Thinking about the structure, a bezel setting is the most secure setting for a stone. It is protective, practical, and non invasive - it does not compromise the original aesthetics of what it is holding. It custom fits what it holds, and its shape is defined by whats inside. In case what I am describing is confusing see attachments of a bezel set stone and setting alone below.

https://img0.etsystatic.com/065/2/5141099/il_340x270.779037864_7toz.jpg

https://s3.amazonaws.com/images.kernowcraft.com/usercontent/img/col-12/11802.jpg

**Comment by faultyserver** [comment]
Limen. (pronounced "lie-men")

> A threshold below which a stimulus is not perceived or is not distinguished from another.

To me, it has the connotation of being "barely perceptible". Like second-nature, the language lets you express your intentions without having to think about how to translate that into something that the language understands. Thoughts flow naturally into code and vice-versa.

**Comment by Willamin** [comment]
> (side note Myst users being called Mysters seems kind of bad...).

Myst users should be called "Mystics"

**Comment by faultyserver** [comment]
Enough people have given me positive feedback on the name Myst that the "gut feeling" I had before is pretty much gone now.

Closing this issue, since it's not really a priority anymore.
