### ISSUE TITLE
More String Additions

### ISSUE THREAD

**Issue by bmulvihill** [myst-lang/myst#136]
Here is list of methods I think would greatly enhance the String type, and would be worthwhile to try and get into `0.5.0`.  Feel free to add to this list, and/or modify it. Most should be fairly simple to implement.

- [x] `chars` - Returns a List w/ chars in a string
- [x] `each_char(&block)` - Iterates through each char, passing it to the given block
- [x] `downcase` - Returns a new string w/ all lowercase letters. Possibly allow encoding case options. This could also be pushed off for future enhancement
- [x] `upcase` - Returns a new string w/ all uppercase letters. Possibly allow encoding case options.  This could also be pushed off for future enhancement
- [x] `chomp` - Returns a new string w/ last carriage return removed
- [x] `chomp(suffix : String) ` - Returns a new string w/ suffix removed 
- [x] `strip` - Returns a new string w/ all leading and trailing whitespace removed
- [x] `rstrip` - Returns a new string w/ all trailing whitespace removed
- [x] `lstrip` - Returns a new string w/ all leading whitespace removed
- [x] `include?(other : String)` - Returns true if the str contains given string or character
- [x] `[](index : Integer)` - Returns the char at the given index.  A negative index is counted from the end of the string. Returns nil if the index falls outside of the string
- [x] `[](start : Integer, length : Integer)` - Returns the substring containing length of characters from start .  A negative index is counted from the end of the string. Returns nil if the index falls outside of the string
- [x] `reverse` - Returns a new string w/ characters in reverse order

**Comment by faultyserver** [comment]
Looks like all of these were implemented in #136. I also think this is a pretty solid list of functions for `0.5.0`, so I'm going to close this as completed.

Any further suggestions for methods can be added as new issues.
