### ISSUE TITLE
Expose `ENV` as a mutable hash of environment variables

### ISSUE THREAD

**Issue by faultyserver** [myst-lang/myst#151]
`ENV` is often an important part of creating command line utilities and otherwise creating automatically-configurable services. Exposing it as a hash in Myst (similar to Ruby/Crystal) would be a key feature of the standard library.

Implementing this should be as simple as passing through to Crystal’s native `ENV` module.

**Comment by Jens0512** [comment]
This should be top level, yes?

**Comment by faultyserver** [comment]
Yes, it should be available at the top level, so inserted directly into `Kernel`.

**Comment by faultyserver** [comment]
This should be done as of #196
