### ISSUE TITLE
Callstack not cleared after `raise` or other exception-based flow.

### ISSUE THREAD

**Issue by faultyserver** [myst-lang/myst#156]
This is a follow up to #92, where the callstack of a program is not being properly managed, and functions that have already executing linger in the stack.

It seems like the issue has less to do with function exits and more to do with exception-based flow. This includes `raise`, as well as `break`, `next`, and `return`, all of which are implemented by raising and rescuing Crystal Exceptions.

My guess is that `callstack.pop` is not happening in all of the right places. More info/examples will be added later.

**Comment by Jens0512** [comment]
Is this the reason for the bug in #155?

**Comment by faultyserver** [comment]
I don't think so. The callstack is only used for printing out errors, it doesn't have any impact on the Interpreter.

I think #155 is a similar issue, though. Somewhere, too many scopes are being popped from the scope stack, and it's ending up at the Kernel instead of looking at the function scope.
