### ISSUE TITLE
Homebrew install script

### ISSUE THREAD

**Issue by jkthorne** [myst-lang/myst#203]
Should there be a homebrew install script?

I have `mtenv` but it would be nice when setting up new environment to have `myst` in homebrew.

**Comment by faultyserver** [comment]
We've got a custom homebrew tap! https://github.com/myst-lang/homebrew-tap. I think it's mostly out of date now, though.

Myst almost definitely will not be added to homebrew-core, it's just too much of a hassle and doesn't provide the best possible experience for developing with Myst (installing multiple versions is hard, switching is even harder, etc.).

The ideal solution for me would be to maintain an official `asdf-myst` plugin for [asdf](https://github.com/asdf-vm/asdf) as I think that provides the best, most versatile experience, and then let the community manage any other installation methods unofficially as people request them.
