### ISSUE TITLE
Allow exception handlers on anonymous function clauses.

### ISSUE THREAD

**Issue by faultyserver** [myst-lang/myst#86]
_This issue has been marked as a "Good First Issue"! If you'd like to tackle this issue as your first contribution to the project, be sure to read the Get Involved section of the README for some help with how to get started._

For consistency with normal method definitions and blocks, anonymous function clauses using the `do...end` syntax should be allowed to define exception handlers:

```myst
func = fn
  ->(2) do
    raise "woops"
  rescue
    :rescued
  end
end

func(2) #=> :rescued
```

The semantics of this should already be in place in the interpreter. The only necessary change should be in the parser, and will likely just be an addition to [`parse_anonymous_function`](https://github.com/myst-lang/myst/blob/master/src/myst/syntax/parser.cr#L299) around this area to call `parse_exception_handler`:

https://github.com/myst-lang/myst/blob/3fbbdc55052318071c8661d9b6d4898e337169c0/src/myst/syntax/parser.cr#L341-L344

For inspiration, you can look at how `parse_optional_block` implements the same thing:

https://github.com/myst-lang/myst/blob/3fbbdc55052318071c8661d9b6d4898e337169c0/src/myst/syntax/parser.cr#L849-L859

There's not too much more to this change. Be sure to add some parser specs around this new syntax. The [exception handler specs for blocks](https://github.com/myst-lang/myst/blob/master/spec/syntax/parser_spec.cr#L2024) should be fairly easy to adapt to use anonymous functions instead.

If you have any questions, feel free to ask in the #help channel in [the discord server](https://discord.myst-lang.org/) or message me directly. Good luck! :)

**Comment by faultyserver** [comment]
Punting to a future version so 0.3.0 can get released sooner rather than later :)

This is great for consistency, but is not necessary for this release.

**Comment by Jens0512** [comment]
I'll task myself with this.
